### ISSUE TITLE
Support semantic-release v16.0.0-beta

### ISSUE THREAD

**Issue by iamchrismiller** [semantic-release/git#100]
The new branches functionality that landed in semantic-release [v16.0.0-beta.1](https://github.com/semantic-release/semantic-release/tree/v16.0.0-beta.1%40beta) is something I need but unfortunately this plugin doesn't yet support it.

I poked around a bit and noticed:

- The new `branch` attribute exists on the root of the context object.
- The branch attribute is [normalized to an object with {name: string} if `branches` is a string](https://github.com/semantic-release/semantic-release/blob/v16.0.0-beta.1%40beta/lib/branches/index.js#L16)

**Comment by pvdlg** [comment]
Release on `@beta` dist-tag as `7.1.0-beta.1`
