### ISSUE TITLE
Command failed: git push --tags <repo_url> HEAD:undefined

### ISSUE THREAD

**Issue by limonte** [semantic-release/git#119]
Failed release: https://travis-ci.org/sweetalert2/sweetalert2/builds/481382150

Open this step to see details

![image](https://user-images.githubusercontent.com/6059356/51424174-09531500-1bd3-11e9-95e4-af1a17f128f2.png)

I fixed this issue by simply adding

```
branch: 'master'
```

to `release.config.js`.

### Expected behavior

`branch` should be `'master'` by default [as per docs](https://semantic-release.gitbook.io/semantic-release/usage/configuration#branch), not `undefined`

### Actual behavior

`Command failed: git push --tags <repo_url> HEAD:undefined`

### Versions

```
- semantic-release@16.0.0-beta.17
- @semantic-release/changelog@3 
- @semantic-release/exec@3 
- @semantic-release/git@7
```

**Comment by pvdlg** [comment]
You have to use `@semantic-release/git` `v7.1.0-beta.x` with semantic-release `v16.0.0-beta`.

**Comment by hashim-sohail** [comment]
Getting the same error on my **Github Actions Workflow** when I run `npx semantic-release@beta`

![SRF](https://user-images.githubusercontent.com/22448789/65489837-6e2edf80-dec5-11e9-8899-ab975e22481b.png)

**Comment by itninja-hue** [comment]
@hashim-sohail  run npx -p @semantic-release/changelog -p @semantic-release/git@beta -p semantic-release@beta  semantic-release --no-ci
