### ISSUE TITLE
Invalid git authentication does not fail build

### ISSUE THREAD

**Issue by jfairley** [semantic-release/git#120]
The `verifyConditions` check in my build seems to fail correctly (because I have the wrong authentication configured), but it doesn't cause the overall build to fail.

<img width="1128" alt="screen shot 2019-01-23 at 10 26 25 am" src="https://user-images.githubusercontent.com/992483/51625033-6f080f80-1ef9-11e9-89ef-798a84a050e0.png">

This build proceeded on where I would expect this message to have put a halt on the whole process.

My build did end up failing down the line where a commit needed to be pushed, but at that point, I was left with a franken-release, with artifacts and release notes (via `@semantic-release/github`) successfully pushed...

**Comment by jfairley** [comment]
My configuration of this plugin is as follows:

```
    ['@semantic-release/git', {
      assets: ['pom.xml']
    }],
```

(I'm releasing a maven project.)

---

My `semantic-release` dependencies are

```
    "@semantic-release/exec": "3.3.0",
    "@semantic-release/git": "7.0.7",
    "semantic-release": "15.12.5"
```

**Comment by pvdlg** [comment]
semantic-release first attempt to the `git push --dry-run` without using any token you might have configured, and if that fails tried again with the token.
This is what happened here. The failure message you see is due to the first attempt without the token and continued because the second attempt worked.

I don't know why it failed later though as you didn't provided the full logs.

**Comment by jfairley** [comment]
Ok, this makes sense. My build failed later, because I tried to do `git push` with the `@semantic-release/exec` plugin.

I'm using CircleCI, and I've just applied a "user SSH key" to my repo, and I no longer get the error I showed in the description. I presume that also means that my manual push will work too, but I don't have a release to make right now. I'll try it next time.

If you happen know the command line pattern for pushing with a specified token, could you paste it? ... I know, you use node libraries in the tool, so no problem if you don't know it off-hand. I'm sure [this](https://stackoverflow.com/questions/18935539/authenticate-with-github-using-token) is the right path.

**Comment by pvdlg** [comment]
The best is to not use `@sematnic-release/exec` to make that push and to use `semantic-release/git` which is meant for that.
I'm going to close this issue ass it seems everything works ass expected.

**Comment by jfairley** [comment]
@pvdlg I understand and agree with your suggestion, and I would if it worked that way.

I'm releasing a maven project and the common paradigm is:

1. Increment the version and commit `pom.xml`.
   * This represents going from `x.y.z-SNAPSHOT` to `${nextRelease.version}`.
   * This is a perfect "prepare" phase and fits well into `@semantic-release/git`.
   * This is also the commit that gets tagged by the `semantic-release` core library.
2. Build and deploy the Java artifacts.
   * This is a perfect "publish" phase. Still looking good.
3. Increment the version and commit `pom.xml`.
   * This represents going from `${nextRelease.version}` back to a snapshot version (some increment of that "next" version, patch increment for me).
   * There is nothing I have found in `semantic-release` that fits this phase, so I'm using `@semantic-release/exec` and doing it during the "success" phase.

Even the `maven-semantic-release` plugin linked from the main docs does this extra stuff. In his case, it's attached to the "publish" phase, but 6-half-dozen.
https://github.com/conveyal/maven-semantic-release/blob/dev/lib/publish.js

**Comment by jfairley** [comment]
Kinda strange to execute a `git push` during "prepare" IMO, when I really think about it.

**Comment by jfairley** [comment]
I guess there's this... https://github.com/semantic-release/git/issues/117

😦
