### ISSUE TITLE
Bug: undefined branch name

### ISSUE THREAD

**Issue by blakedietz** [semantic-release/git#137]
### Config

https://github.com/blakedietz/vscode-nested-tags/blob/master/package.json#L96

https://github.com/blakedietz/vscode-nested-tags/blob/master/package.json#L131

## What happened

For some reason my semantic release user is able to release, but the branch it's deploying to is master.

https://github.com/blakedietz/vscode-nested-tags/tree/undefined

## What did you expect to happen

I expected that my changelog file was to be published to master instead of "undefined".

**Comment by pvdlg** [comment]
Can you provide the logs of the problematic run?

**Comment by vadimsgaliskins** [comment]
@blakedietz you seem to have beta version of semantic-release package
https://github.com/blakedietz/vscode-nested-tags/blob/master/package.json#L46
but stable version of @semantic-release/git plugin
https://github.com/blakedietz/vscode-nested-tags/blob/master/package.json#L32

Switching to beta release of @semantic-release/git helped me solve this exact issue in my workflow.

**Comment by pvdlg** [comment]
The version discrepancy pointed out by @blakedietz is most likely the cause of this problem.
