### ISSUE TITLE
GitLab Tokens not used.

### ISSUE THREAD

**Issue by keplersj** [semantic-release/git#15]
Looking through the documentation it looks like this plugin will use the `GITHUB_TOKEN` or `GH_TOKEN` variables if present, but not the `GITLAB_TOKEN` or `GL_TOKEN` variables. Can this functionality be added?

**Comment by keplersj** [comment]
Setting `GIT_CREDENTIALS` to `gitlab-ci-token:$GITLAB_TOKEN` in GitLab works very well.

**Comment by gr2m** [comment]
Can we close this, as it’s documented in the README?

> For GitLab theGIT_CREDENTIALS value has to be set with gitlab-ci-token:<personal_access_tokens>

**Comment by pvdlg** [comment]
If `GITLAB_TOKEN` is set we could defined (in the code) the Git credential to `gitlab-ci-token:<GITLAB_TOKEN>` automatically. But I'm not sure how well this is supported as it's not part of the GitLab doc.
Does this work in both public and private GitLab instance? Is it the officially supported way to access the remote repository? Or is it subject to change in the future?
