### ISSUE TITLE
What is the correct way to use this plugin with dev branch?

### ISSUE THREAD

**Issue by joshuaavalon** [semantic-release/git#150]
From the README of semantic-release/semantic-release

>  Triggering a release
> ...
> - Develop on a `dev` branch and merge it to the release branch (i.e. `master`) once you are ready to publish. **semantic-release** will run only on pushes to the release branch.

However, semantic-release/git will merge changes to `master` instead of `dev` which leads `master` ahead of `dev`.

**Comment by pvdlg** [comment]
Per the documentation this plugin:
> Create a release commit, including configurable file assets.

It will not merge anything...
Please read the semantic-release documentation (https://semantic-release.gitbook.io/semantic-release/) and use the support channels (https://semantic-release.gitbook.io/semantic-release/#get-help) if you have specific questions.
