### ISSUE TITLE
Unable to configure  'message' option for git plugin

### ISSUE THREAD

**Issue by padamstx** [semantic-release/git#172]
This issue is similar to https://github.com/semantic-release/git/issues/89, but I don't understand the solution given there.

I am trying to configure the git plugin so that when it creates the release commit, it does NOT include
the `[skip ci]` part in the commit message.   The reason for this is that I actually want a tagged release build to be triggered in Travis when the new release tag is pushed back to the github server, but currently that release build is being rejected by Travis due to the commit message.
I'm following the examples provided in the small bits of relevant documentation that I could find, but it's just not working for me as the default message is still being used.

Here is my .releaserc file:
```
{
  "branch": "master",
  "verifyConditions": ["@semantic-release/changelog", "@semantic-release/github"],
  "debug": true,
  "prepare": [
    {
      "path": "@semantic-release/exec",
      "cmd": "bumpversion --allow-dirty --current-version ${lastRelease.version} --new-version ${nextRelease.version} patch"
    },
    "@semantic-release/changelog",
    "@semantic-release/git"
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    [
      "@semantic-release/git", 
      {
        "message": "chore(release): ${nextRelease.version} release notes\n\n${nextRelease.notes}"
      }
    ]
  ],
  "publish": [
    {
      "path": "@semantic-release/github"
    }
  ]
}
```
What am I doing wrong???  :)

**Comment by pvdlg** [comment]
Please see https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md

I'm not really why you ended up having all that in your config...I'm guessing the only thing you want here is the `plugins` property.

**Comment by padamstx** [comment]
@pvdlg Thanks for the quick response!
I think the main reason that I have all that in my .releaserc file is that I don't fully understand the docs that talk about configuration.
These are the main things that I want to do (this is for a python project):
1. run the "bumpversion" command to create a commit that updates a couple of files with the new version # (this will result in a commit with message like "Bump version: 1.3.0 → 1.4.0").
2. run the changelog plugin to update CHANGELOG.md (this currently results in a commit with message like "chore(release): 1.4.0 [skip ci]"
I really just want the "release commit" to not include "skip ci".

What is currently happening is that the release commit (which has the new release tag associated with it) gets pushed back to the github server along with the tag.  A tagged release build is then triggered in Travis, which is immediately rejected due to the presence of "skip ci" in the message of the tagged commit.
Could you suggest a configuration that would achieve this?
Thanks in advance!

**Comment by pvdlg** [comment]
You can use this:
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    [
      "@semantic-release/git", 
      {
        "message": "chore(release): ${nextRelease.version} release notes\n\n${nextRelease.notes}"
      }
    ],
    [
      "@semantic-release/exec", 
      {
        "prepareCmd": "bumpversion ...."
      }
    ],
    "@semantic-release/github"
  ]
}
```

It seems your bumpversion command is wrong as you specify `patch` in it. Not all the releases will be patches. I don't know how bumpversion work though so I don't know what's the right command.

You probably also want to set the `assets` option of the `@semantic-release/git` to define the file that you want to commit (by default `package.json` and `CHANGELOG.md`).

Finally I don't think it's correct to remove the `skip ci` from the commit message. There is no reason to trigger a Travis on that commit. I don't understand why you want Travis to run on that commit....

**Comment by pvdlg** [comment]
For information, if you need help with a configuration you should ask on the proper channel: https://github.com/semantic-release/semantic-release#get-help. This way other users can help you.

**Comment by padamstx** [comment]
> For information, if you need help with a configuration you should ask on the proper channels: https://github.com/semantic-release/semantic-release#get-help. This way other users can help you.

Thanks for that link...

**Comment by padamstx** [comment]
> It seems your bumpversion command is wrong as you specify `patch` in it. Not all the releases will be patches. I don't know how bumpversion work though so I don't know what's the right command.

It turns out that using "patch" in that command is ok as we're explicitly giving bumpversion the old and new version #'s.   We have to provide something for that option so "patch" is the likely candidate even though it is overridden by specifying the new version explicitly.

> 
> You probably also want to set the `assets` option of the `@semantic-release/git` to define the file that you want to commit (by default `package.json` and `CHANGELOG.md`).

We really only want CHANGELOG.md to be committed in the "release commit", so I'll change my config accordingly.   Also, this is a python project so I don't have a package.json file that is to be committed/pushed back to the repo.

> 
> Finally I don't think it's correct to remove the `skip ci` from the commit message. There is no reason to trigger a Travis on that commit. I don't understand why you want Travis to run on that commit....

In our case, we have a Travis "deploy" step to publish the tagged release to pypi (this is a python project) and it is configured to run only on a tagged release build.  What I'm seeing is that semantic-release tags the release commit, then pushes the two new commits (bumpversion commit and the release commit) along with the new release tag back to the remote repo.   The issue is just that the tagged commit (the release commit) contains "[skip ci]" which prevents Travis from kicking off the tagged release build.
If there was a way to have semantic-release publish the resulting tagged release of the python project to pypi (similar to how it can be used to publish a node project to npm), I could do that instead I think.

I'll give your config suggestion a try.
Many thanks for your help!

**Comment by pvdlg** [comment]
> In our case, we have a Travis "deploy" step to publish the tagged release to pypi (this is a python project) and it is configured to run only on a tagged release build. What I'm seeing is that semantic-release tags the release commit, then pushes the two new commits (bumpversion commit and the release commit) along with the new release tag back to the remote repo. The issue is just that the tagged commit (the release commit) contains "[skip ci]" which prevents Travis from kicking off the tagged release build.
> If there was a way to have semantic-release publish the resulting tagged release of the python project to pypi (similar to how it can be used to publish a node project to npm), I could do that instead I think.

That's not really how semantic-release is meant to work. I didn't realized bumpversion was creating a commit...I though it was just updating the version in some files.
I don't think you should use bumpversion at all then.
semantic-release is meant to make the publish, not to have something else doing it in reaction of the tag being created.
You should remove bumpversion and use the `@semantic-release/exec` plugin to:
- update the files you want to update on `prepare` step
- publish the package on your registry on the `publish` step

**Comment by padamstx** [comment]
Ok, I'll try to work towards that...  I'll use the "get-help" link above... Hopefully there are others that are already using semantic-release with python projects that do the publish step.
Thanks again!

**Comment by pvdlg** [comment]
Thanks! Someone might also consider creating a plugin to do the release of a Python project.
I imagine it would be something similar to what we do in  https://github.com/semantic-release/npm

**Comment by padamstx** [comment]
Just a follow-up in case anyone else encounters this same problem...

Here's the config that I ended up with, which is just slightly different than what @pvdlg suggested above:
```
{
  "debug": true,
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    [
      "@semantic-release/exec", 
      {
        "prepareCmd": "bumpversion --allow-dirty --current-version ${lastRelease.version} --new-version ${nextRelease.version} patch"
      }
    ],
    [
      "@semantic-release/git", 
      {
        "message": "chore(release): ${nextRelease.version} release notes\n\n${nextRelease.notes}"
      }
    ],
    "@semantic-release/github"
  ]
}
```

With this config, my travis build (python project) is able to modify a couple of files to bump up the version # (to the new version determined by semantic-release), then update the changelog, creates the new tag (which points at the release commit), then pushes both commits and the tag back to the remote repo.
I removed the "skip ci" part of the git plugin's commit message so that the push of the new tag would in fact trigger a tagged release build in Travis.   I do this so that the pypi deploy step in my Travis config will be executed to publish the new version of the python project to pypi.  For reference, here's the
deploy section of my .travis.yml file:
```
deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      python: '3.5'
      branch: master
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    repository: https://upload.pypi.org/legacy
    skip_cleanup: true
    on:
      python: '3.5'
      tags: true
```
Next step will be to try to configure semantic-release's publish step to publish the new version of the project to pypi, thus avoiding the need to kick off the tagged release build at all.

Thanks again to @pvdlg for all the help.

**Comment by ms-dosx86** [comment]
For anyone else who is facing the same problem try to remove "@semantic-release/git" from "prepare" and "verifyConditions". Having defined it in "plugins" section was enough for me.
