### ISSUE TITLE
Feature Request: Tag only publish

### ISSUE THREAD

**Issue by bengreenier** [semantic-release/git#178]
Hi folks, 

I'm interested in the ability to push a commit containing assets to a tag, but not to the core release branch. The pattern I'm interested in is like what [jquery](https://github.com/jquery/jquery) is doing, shipping populated `dist/` only [in tags](https://github.com/jquery/jquery/tree/3.4.1/dist), but not in [master/dev branches](https://github.com/jquery/jquery/tree/master/dist).

Would ya'll be willing to accept a PR adding support for that? Maybe something [like this](https://github.com/semantic-release/git/compare/master...bengreenier:feature/empty-branch-tags-only)? 

P.S. Thanks for creating something great and reliable. 👍

**Comment by bengreenier** [comment]
Upon further investigation, looks like this may not be possible to support (at least, within the constraints this plugin operates). The core package seems to have logic that enforces previous versions are only found [if there's a tag that's directly a part of the release branch history](https://github.com/semantic-release/semantic-release/blob/master/lib/get-last-release.js#L27) which seems like a blocker. Probably also makes it a bit bigger of a concern/conversation to make this kind of change.

**Comment by pvdlg** [comment]
It seems that JQuery make tags that doesn't reference any commits. We need to have the tags being associated with a commit so we can determine the commits done since the last release.

So unfortunately we won't be able to support the feature you are requesting.
