### ISSUE TITLE
on GitLab, a release job launches 2 pipelines

### ISSUE THREAD

**Issue by oupala** [semantic-release/git#179]
It appears that on GitLab, a release job launches 2 pipelines.

I think that while there only 1 commits, there is to pushes. :

- one push to push the commit
- one push to push the tag

Each push launches a pipeline, which result in 2 pipelines with `[skip ci]` comment in the commit message. This not really annoying as the pipelines are not launched. But this generates noise on the pipelines list.

In your opinion, is that behavior normal?

**Comment by pvdlg** [comment]
That seems to be specific to GitLab CI or to your specific configuration as it doesn't on other CIs.
Travis for example doesn't trigger anything on a release because you can configure it to not build tags and the `[skip ci]` in the commit message doesn't trigger a build for the release commit.

I imagine this can be configured in GitLab CI as well.

Please use [Spectrum](https://spectrum.chat/semantic-release) to ask support questions, this way other users can help you with your config. We try to reserve the GitHub issue tracker for bugs and feature requests.

**Comment by oupala** [comment]
I am looking into GitLab to see is there is something to configure here.

Can you confirm that the git plugin is pushing twice? Once for the commits, once for the tag.

**Comment by oupala** [comment]
Unfortunately, I haven't found any way to prevent GitLab CI from launching two pipelines.

If anyone has an idea about this issue, please comment!

**Comment by edmundo096** [comment]
@oupala Check the [GitLab CI workflow:rules](https://docs.gitlab.com/ee/ci/yaml/README.html#workflowrules) config to set conditionals on your pipelines.

For example, this _may_ solve your issue (at least for the commit message, I haven't tested it though, you may need to tackle the tag as well) or serve as a starting point for you:

```yaml
workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip ci\]/
      when: never
    - when: always
```

Check https://docs.gitlab.com/ee/ci/variables/predefined_variables.html for more predefined variables.

Hey @pvdlg you may consider putting a note comment on the GitHub issue templates telling to check out/use Spectrum for general questions.

**Comment by oupala** [comment]
Adding the 5 lines from @edmundo096's comment does not change anything: two pipelines are still launched.

I did not knew about this `workflow` keyword for GitLab CI, so I might be using it wrongly.

Here is the workflow I'm using:

```
workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /skip ci/
      when: never
    - when: always
```

The strange thing is that if **my** commit message contains `skip ci`, no pipeline is launched, not even mine.

But if my commit message does not contain `skip ci`, my pipeline is launched and generates a release which launches the two pipelines even if the commit message is `chore(release): 1.5.0 [skip ci]`.

It seems that rules are different depending on the way commits are done. If the commit is made by an external actor (me), the rule is applied. But if the commit is made by GitLab CI, the rule is **not** applied.

Any help to understand this strange behavior is welcome.

**Comment by edmundo096** [comment]
I have left this kind of work but as far I remember the semantic common workflow is:

1. Create a PR with a feature to your branch that triggers semantic release (e.g. master).
2. When PR is merged (after proper test passed ideally), a merge commit on master (as per our example) is created.
3. Your CI/CD pipeline runs.  
  When the semantic release step/job runs (if properly configured) it would commonly read changes, compare tags, decide version bump, etc. If your config you want to save the update to `CHANGELOG.md` or the version bump on `package.json` for example, you would need another commit (this commit should have the `[skip cd]`, continue reading to see why) which is created by `@semantic-release/git` plugin as far I remember. This commit will be then pushed into your master branch.  
So your CI/CD would run again as per this new changelog update / version bump commit, that is why the GitLab workflow rules are for, as they wont trigger a 2nd time by this automatic chore commit which should have the `[skip ci]`.

This may help:

The red branch is `master`, the green one is the feature branch, over a PR (or MR, Merge Request on GitLab)
![image](https://user-images.githubusercontent.com/2168903/74626765-419a8f00-5116-11ea-9258-0540a0b21431.png)

Last note, your job may trigger as well by a Git tag created along the version bump / changelog update commit, but this depends if your have configured your CI/CD with such trigger.
