### ISSUE TITLE
Missing step in "Add the GPG keys to your CI environment" 

### ISSUE THREAD

**Issue by MatthewMi11er** [semantic-release/git#18]
Perhaps I'm missing something but in the [README](https://github.com/semantic-release/git/blob/508c7c84aafd0890d3c15aaf1bb17e66630466d7/README.md) the instructions for adding the GPG key appear to be missing a step.
Doesn't there need to be a `gpg --import` or something to tell GPG where to find the specified key?

**Comment by gr2m** [comment]
I have no experience with `pgp` myself, maybe @pvdlg can help out once he’s back next week

**Comment by pvdlg** [comment]
if we would do `gpg --import` we would have a prompt to enter the passphrase when a commit is done. As we run on the CI we can't enter the passphrase in the prompt.

Instead we generate a temporary script with `echo '/usr/bin/gpg2 --passphrase ${GPG_PASSPHRASE} --batch --no-tty "$@"' > /tmp/gpg-with-passphrase && chmod +x /tmp/gpg-with-passphrase` and we use it to sign the commit with `git config gpg.program "/tmp/gpg-with-passphrase"`.

Do you experience an issue to sign commits when you follow the doc in the README?

**Comment by MatthewMi11er** [comment]
I under the purpose of the script part, but it has no reference to the key placed at `/tmp/git_gpg_keys.asc`, so how does it know what key to use?

 Also I don't think you need the password to import the key into the keychain, only to do the signing which is what the script solves.

**Comment by pvdlg** [comment]
After more testing, you are correct the `import` step is missing. Added in #19.
