### ISSUE TITLE
.releaserc.js ErrorEXError [JSONError]: Unexpected end of JSON input while parsing near ''

### ISSUE THREAD

**Issue by unlight** [semantic-release/git#189]
@semantic-release/git@9.0.0

Looks like semantic-release/git trying to parse config as json, even if it defined in javascript file

`.releaserc.js`
```
module.exports = {
    plugins: [
        '@semantic-release/commit-analyzer',
        '@semantic-release/release-notes-generator',
        '@semantic-release/changelog',
        [
            '@semantic-release/npm',
            {
                pkgRoot: 'dist',
            },
        ],
        '@semantic-release/github',
        '@semantic-release/git',
    ],
};
```
![image](https://user-images.githubusercontent.com/301732/73490932-f7e83f80-43c6-11ea-979d-9adfd69794af.png)

**Comment by pvdlg** [comment]
The problem is with your `package.json` that seems to contains invalid JSON.

**Comment by unlight** [comment]
package.json is valid, seems that problem with node 13.7 or ci/cd, published from local machine - no error, and switch ci/cd to node v12.14.1 - no errors

**Comment by unlight** [comment]
Sorry. Shell pipeline issue with manipulation json...
