### ISSUE TITLE
push to protected master branch without admin permissions

### ISSUE THREAD

**Issue by pheenomenon** [semantic-release/git#205]
Our master branch is protected with `At least 1 approving review is required by reviewers with write access.` . and we do not want our `bot` user to have admin permission. 
On using the '@semantic-release/git' plugin to update version # in package.json, we get the error:

`remote: error: Required status check "Travis CI - Branch" is expected. At least 1 approving review is required by reviewers with write access.        
436`
Is there a best practice recommendation. This was also discussed here https://github.com/semantic-release/github/issues/175 , but don't see a workaround. Any pointers will help.

**Comment by travi** [comment]
Keep in mind that semantic-release interacts with GitHub as one of the users that your have granted permission to interact with you repos. semantic-release does not have any ability to work around the permissions that are enforced by GitHub. 

The only exception that GitHub allows to the branch protection that you describe is to not enforce for users with admin level permissions. 

If you desire more flexibility than GitHub currently enables, your best bet is contacting GitHub support and describing the enhancements that you would want.
