### ISSUE TITLE
Add getLastRelease plugin

### ISSUE THREAD

**Issue by mattyclarkson** [semantic-release/git#26]
We don't publish our package on NPM but use the `semantic-release/git` to perform tagging. Beign able to get the last release from our tags would be really useful. It seems it would make sense to contribute this functionality to this project.

There is an archived project [semantic-release/last-release-git-tag](https://github.com/semantic-release/last-release-git-tag) that used to do this. What is the history there? Would it make sense to bring back that functionality to this project?

**Comment by mattyclarkson** [comment]
Oh, it seems it does it already [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-last-release.js#L32-L37)

**Comment by pvdlg** [comment]
See semantic-release/semantic-release#613.
This feature has been moved in the core on version `13.0.0` and above (currently published on the dist-tag `@next`).
