### ISSUE TITLE
Incompatibility with 13.x, double creation of tag.

### ISSUE THREAD

**Issue by mattyclarkson** [semantic-release/git#27]
The `13.x` series of `semantic-release` creates the `git tag`. This plugin also attempts to create the tag, which fails.

There is a regression in `13.x`. The previous behaviour was:

  * `fix(abc): this will trigger semantic-release` ← `npm publish`
  * `chore(release): v1.0.0 [skip ci]` ← `tag v1.0.0`

If we fix up this plugin to not create the tag, the functionality will be:

  * `fix(abc): this will trigger semantic-release` ← `npm publish` ← `tag v1.0.0`
  * `chore(release): v1.0.0 [skip ci]`

Which is *more* correct, because the tag actually points to the location of the published package, but going to that tag in `git` won't have the updated changelog/`package.json`.

The ideal result would be:

  * `fix(abc): this will trigger semantic-release`
  * `chore(release): v1.0.0 [skip ci]` ← `npm publish` ← `tag v1.0.0`

**Comment by mattyclarkson** [comment]
`.releaserc.json`

```json
{
  "verifyConditions": [
    "@semantic-release/changelog",
    {
      "path": "@semantic-release/npm",
      "npmPublish": false
    },
    "@semantic-release/git",
    "@semantic-release/github"
  ],
  "publish": [
    "@semantic-release/changelog",
    "@semantic-release/git",
    "@semantic-release/github"
  ]
}
```

I assume removing the `@semantic-release/git` from the publish would stop the release commit being created, which is super useful for updating the project. I upgraded to `13.x` because of the following problem that was occuring on CircleCI:

```
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git push --tags git+https://github.com/ef-carbon/dom.git HEAD:master
fatal: Unable to find remote helper for 'git+https'


    at makeError (/home/circleci/repo/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/home/circleci/repo/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: Unable to find remote helper for \'git+https\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags git+https://github.com/ef-carbon/dom.git HEAD:master',
  timedOut: false,
  killed: false }
```

**Comment by mattyclarkson** [comment]
Hmm, the `3.0.0` release says it removed the git tag creation.

**Comment by mattyclarkson** [comment]
Ah, [this code](https://github.com/semantic-release/semantic-release/blob/39536fa34e64234fe530adb37b19380d5fa6a699/index.js#L82-L89) looks like it **does** move the git tag to the correct place. Can't figure out why I'm getting the duplicate tag problem though.

**Comment by mattyclarkson** [comment]
This is the build log:

```
[Semantic release]: There is no previous release, the next release version is 1.0.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Create tag v1.0.0
[Semantic release]: Call plugin publish
[Semantic release]: Create CHANGELOG.md
[Semantic release]: Add CHANGELOG.md to the release commit
[Semantic release]: Add package.json to the release commit
[Semantic release]: Found 1 file(s) to commit
[Semantic release]: Creating tag v1.0.0
[Semantic release]: Published Git release: v1.0.0
[Semantic release]: Create tag v1.0.0
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.com/ef-carbon/nightingale-backend.git HEAD:master
To https://[secure]@github.com/ef-carbon/nightingale-backend.git
 ! [rejected]        v1.0.0 -> v1.0.0 (already exists)
error: failed to push some refs to 'https://[secure]@github.com/ef-carbon/nightingale-backend.git'
hint: Updates were rejected because the tag already exists in the remote.


    at makeError (/home/circleci/repo/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/home/circleci/repo/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://[secure]@github.com/ef-carbon/nightingale-backend.git\n ! [rejected]        v1.0.0 -> v1.0.0 (already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/ef-carbon/nightingale-backend.git\'\nhint: Updates were rejected because the tag already exists in the remote.\n',
  failed: [secure],
  signal: null,
  cmd: 'git push --tags https://[secure]@github.com/ef-carbon/nightingale-backend.git HEAD:master',
  timedOut: false,
  killed: false }
error Command failed with exit code 1.
```

**Comment by mattyclarkson** [comment]
Actually, I don't the ideal result can be supported:

  * `fix(abc): this will trigger semantic-release`
  * `chore(release): v1.0.0 [skip ci]` ← `npm publish` ← `tag v1.0.0` 

Because the NPM plugin bumps the version **and** publishes all in one. It would need to be:

  * bump version
  * perform git commit
  * perform git tag
  * npm publish

**Comment by pvdlg** [comment]
It seems you want to use the npm plugin as you mention it in your comments, but it's not configured for the publish step in your configuration.

Also it seems you are using the version `2.x` of this plugin with `semantic-release@13.x` that are not compatible. You have to upgrade to version `3.x` of the plugin if you use `semantic-release@13.x`.

**Comment by mattyclarkson** [comment]
I thought I had that version, I'll double check and try again, thanks for the help 😊 

Is it possible to start adding `peerDependencies` to these plugins so that `yarn`/`npm` warn when they are installed and are not compatible with the core module?

Personally, I would find it clearer if `semantic-version` had no plugins built in and the plugins (and versions) were managed by the project. If `semantic-version` requires that some plugins need to be installed then they could be listed in it's `peerDependencies` so that `yarn`/`npm` would tell me to install them (e.g. `@semantic-version/npm`, etc). Then each plugin can have a `peerDependency` on `semantic-version` that denotes which version it is compatible with. This would provide warnings on `yarn install` when plugins/core are not compatible.

It would mean that the core install would become longer `yarn add -D semantic-version @semantic-version/npm ...` but more explicit.

**Comment by pvdlg** [comment]
> Is it possible to start adding peerDependencies to these plugins so that yarn/npm warn when they are installed and are not compatible with the core module?

I think I did that as some point, but reverted it for a reason I can't remember. I'll check that out.

> It would mean that the core install would become longer yarn add -D semantic-version @semantic-version/npm ... but more explicit.

I think we can add `peerDependencies` in plugins and keep the npm and GitHub plugins installed by default. They are used by default and most `semantic-release` users use them that way. So I don't see much reasons to force most of the users to add to extra 2 dependencies.
But the `peerDependencies` make perfect sense.

**Comment by mattyclarkson** [comment]
What happens when I install `@semantic-release/npm` as a `devDependency`? Does `semantic-release` pick up **my** installed version or the plugin that is installed as a dependency of itself?

**Comment by pvdlg** [comment]
That's an npm thing and not really related to semantic-release. If you have a module that is depended on multiple times, npm would install the highest version that match the range defined by each dependent. So if you `@semantic-release/npm` manually and `semantic-release` defines it as a dependency, the highest version that match both range will be used.

**Comment by mattyclarkson** [comment]
Duh, yeah, sorry, was thinking the dependencies would be nested. Thanks for adding the peer dependency :)
