### ISSUE TITLE
Include changelog in published tarball to npm

### ISSUE THREAD

**Issue by SimenB** [semantic-release/git#3]
I haven't tested, but from what I can understand from the README the npm plugin has to be run before this plugin.

How can I then write a changelog to disk which is included in that published tarball?

Should the writing of a changelog part be its own plugin?

I don't really want the commit, but I understand that the plugin can't really create a full changelog for all previous releases from all time, so I don't mind the commit either 🙂 

(opening issue here as I was directed from https://github.com/semantic-release/semantic-release/issues/543)

**Comment by pvdlg** [comment]
> I haven't tested, but from what I can understand from the README the npm plugin has to be run before this plugin.

Only if you want to commit the tarball and the updated `package.json` which the main use case of this plugin.

> How can I then write a changelog to disk which is included in that published tarball?

You can run them the other way around. the `git` plugin will generate the changelog and do the commit (without the tarball not the updated `package.json`) then the `npm` will release with the changelog.

But I don't know if this workflow serves any purpose as including a changelog in the tarball is not really useful. The changelog won't be displayed on npmjs.org. And I don't think any user will browse their `node_modules` to find the changelog. They would instead go to the Github repo.
Even if you think your users would browse the `node_modules` folder, then just put a link to the changelog in your readme.

> Should the writing of a changelog part be its own plugin?

At that point, I don't think so, as the git repo is the only place for which it make sense to push a changelog. As explain above I'm not sure there is any reason to include it the tarball.

**Comment by SimenB** [comment]
>Only if you want to commit the tarball and the updated package.json which the main use case of this plugin.

I don't really want either - I just want a changelog inside the tarball. This repo is probably the wrong place to discuss it, I can open up an issue in a more fitting repo, if you want? 🙂

>including a changelog in the tarball is not really useful

I disagree 😀

> The changelog won't be displayed on npmjs.org

That's IMO just a missing feature from npmjs.org, and yarnpkg.com currently renders it - see e.g https://yarnpkg.com/en/package/yargs

(Yarn's website is way better than npm's in most regards, rendering the changelog being one of them 🙂)

>And I don't think any user will browse their node_modules to find the changelog.

I do, for one. I explore code in node_module quite often, especially if I'm upgrading or debugging - going back and forth from the browser and my IDE is cumbersome. As a bonus having the changelog on disk is very useful for offline development (e.g. on planes).

**Comment by pvdlg** [comment]
So you have multiple options:
- Run a script in the `prePublishOnly` hook to generate the changelog. Something like [standard-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/standard-changelog)
- Run the `git` plugin before `npm`
- Write a `semantic-release` plugin that generate the changelog and run it before `npm`

Closing as it's not related to this repo and there is several solutions to achieve your workflow

**Comment by SimenB** [comment]
Sounds good, thanks for the pointers!
