### ISSUE TITLE
Tag not on commit?

### ISSUE THREAD

**Issue by filipvh** [semantic-release/git#30]
In my previous projects

    "@semantic-release/git": "^2.0.1",
    "semantic-release": "^11.0.2"

now:
    "@semantic-release/git": "^3.0.0",
    "semantic-release": "^12.4.1"

changelog.md and updated package(-lock).json is commited
but the tag not

**Comment by pvdlg** [comment]
As mentioned in the [v3.0.0](https://github.com/semantic-release/git/releases/tag/v3.0.0) of the git plugin, it requires semantic-release >=13.0.0. That's most likely your issue.

Feel free to re-open if it doesn't solve your it
