### ISSUE TITLE
body too long

### ISSUE THREAD

**Issue by y-nk** [semantic-release/git#331]
the release notes are in the commit body, but i have rules enforced to limit the size of the commit body. is there a way to pass arguments to the commit command ?

**Comment by dennisjlee** [comment]
@y-nk I also hit a problem like this (using `commitlint`). Not sure if you're also using that, but I was able to work around the problem by configuring commitlint to ignore changes that look like the ones from @semantic-release/git.

I set up this config at `commitlint.config.cjs` (you could also use `commitlint.config.js`)
```
const automaticCommitPattern = /^chore\(release\):.*\[skip ci]/;

const commitlintConfig = {
  "extends": [
    "@commitlint/config-conventional"
  ],

  ignores: [
    commitMsg => automaticCommitPattern.test(commitMsg)
  ]
};

module.exports = commitlintConfig;
```

**Comment by y-nk** [comment]
Thanks @dennisjlee that's a good workaround 🙏

**Comment by waldronmatt** [comment]
Thanks a ton @dennisjlee that worked for me, spent hours trying to troubleshoot this issue.
