### ISSUE TITLE
Add flags to git commit command

### ISSUE THREAD

**Issue by rub3n-san** [semantic-release/git#505]
Hi,

I use [husky](https://typicode.github.io/husky/) to setup some pre commit hooks, and I would like to skip them on the release with the flag `--no-verify`.
Is there any possibility to add this feature?

**Comment by travi** [comment]
Husky provides steps to prevent those hooks being configured in ci workflows.  What prevents those from handling your use case?

**Comment by rub3n-san** [comment]
You are right, @travi thank you so much for the input.

For future reference: https://typicode.github.io/husky/how-to.html#ci-server-and-docker
