### ISSUE TITLE
README file wrong link

### ISSUE THREAD

**Issue by yaroslav-007** [semantic-release/git#510]
Hello,

On https://github.com/semantic-release/git/blob/5e30d7a5510a035d9c5d7fabf6959adeeccb0e60/README.md?plain=1#L186
link should point to `https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account`

**Comment by travi** [comment]
we would welcome a PR to update the link

**Comment by yaroslav-007** [comment]
Hello,

Please review https://github.com/semantic-release/git/pull/511
