### ISSUE TITLE
[Security] Lodash vulnerability

### ISSUE THREAD

**Issue by tiwarishubham635** [semantic-release/git#517]
This library depends on vulnerable versions of lodash
Here is the detailed information - https://github.com/advisories/GHSA-35jh-r3h4-6jhm

Currently this library uses lodash v4.17.4 which should be updated

**Comment by travi** [comment]
> [!IMPORTANT]
> _please_ use our [security policy](https://github.com/semantic-release/git/security/policy) in the future for potential security related issues.

> Currently this library uses lodash v4.17.4

that version is defined as the lower bound of the defined _range_ for the dependency. the patched version is also in-range. simply update your lockfile. you do not need to depend on an update of this package to update to the latest version
