### ISSUE TITLE
Question: remove `[skip ci]` from commit message

### ISSUE THREAD

**Issue by zirkelc** [semantic-release/git#521]
HI,

I was wondering is there an easy way to remove the `[skip ci]` suffix from the commit message when generating the release notes?

**Comment by travi** [comment]
i transferred to this repo because your question is related to the git plugin rather than the release-notes-generator where you originally filed the issue. 

you can find details about adjusting the commit message under the [options for this plugin](https://github.com/semantic-release/git#options)
