### ISSUE TITLE
Add documentation regarding Git host push permission configuration

### ISSUE THREAD

**Issue by Aghassi** [semantic-release/git#71]
Hello,

I've read through all the docs on setting this up, and have done it on multiple repos. This issue persists on a repo we have that has the same keys as another repo, but consistently fails to deploy.

1. Both have the following in package.json

```json

  "release": {
    "prepare": [
      "@semantic-release/npm",
      "@semantic-release/git"
    ]
  }
```

2. Both have the same `GITHUB_TOKEN` and `GITHUB_URL`, and run release via ` GITHUB_URL=$GITHUB_URL GITHUB_TOKEN=$SERVICE_GITHUB_TOKEN yarn release` where `yarn release` is just `semantic-release`. They run on CircleCI in the same org context.
3. Both have branch protection enabled for status checks etc on master
<img width="974" alt="screen shot 2018-08-05 at 11 49 39 am" src="https://user-images.githubusercontent.com/3680126/43688855-ad1369e4-98a5-11e8-942a-7ad858c51d27.png">
4. Both have a repository field in package.json with structure:

```json
  "repository": {
    "url": "git@github.enterprise.com:Org/Repo.git",
    "type": "git"
  },
```

However, even with all of this, I still see on the failing repo when it tries to deploy.
```bash
[18:27:36] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[18:27:36] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.enterprise.com/Org/Repo.git HEAD:master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 2 of 2 required status checks are expected.        
To https://[secure]@github.enterprise.com/Org/Repo.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://[secure]@github.enterprise.com/Org/Repo.git'


    at makeError (/home/circleci/project/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/circleci/project/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \nremote: error: 2 of 2 required status checks are expected.        \nTo https://[secure]@github.enterprise.com/Org/Repo.git\n ! [remote rejected] HEAD -> master (protected branch hook declined)\nerror: failed to push some refs to \'https://[secure]@github.enterprise.com/Org/Repo.git\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.enterprise.com/Org/Repo.git HEAD:master',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/git' }
{ Error: Command failed: git push --tags https://[secure]@github.enterprise.com/Org/Repo.git HEAD:master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 2 of 2 required status checks are expected.        
To https://[secure]@github.enterprise.com/Org/Repo.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://[secure]@github.enterprise.com/Org/Repo.git'


    at makeError (/home/circleci/project/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/circleci/project/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \nremote: error: 2 of 2 required status checks are expected.        \nTo https://[secure]@github.enterprise.com/Org/Repo.git\n ! [remote rejected] HEAD -> master (protected branch hook declined)\nerror: failed to push some refs to \'https://[secure]@github.enterprise.com/Org/Repo.git\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.enterprise.com/Org/Repo.git HEAD:master',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/git' }error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c semantic-release
Directory: /home/circleci/project
Output:
```

At this point, I'm all out of ideas as to where this problem is stemming from. Would love some guidance as to why one repo would experience this issue, but the other is completely fine. I have at least a dozen repos working with similar setups with the same token and don't have this issue.

**Comment by pvdlg** [comment]
Your GitHub settings allow to push to this branch only when:
- The commit have been pushed to another branch before
- The 2 status check have passed
- You open a PR and merge it

The `@semantic-release/git` plugin pushes directly to your branch.
You have to make sure to no check "Include administrators" and use a token associated with an administrator.

**Comment by Aghassi** [comment]
@pvdlg Thank you! Smallest detail that I overlooked. Would be nice to get some feedback on that because I had no idea. Can that be listed in the [README](https://github.com/semantic-release/git/blob/master/README.md) somewhere? Or maybe in the [Configuration CI](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#ci-configuration) area? I can make a PR, just want to know where is best to note that the token provided *must* have admin if using status checks.

**Comment by pvdlg** [comment]
Yes it should be added to the README of this plugin.
I want to check if there is a better way to do it that doesn't require using an admin user.
The doc also has to be generic enough as the plugin can be used with any Git host.
