### ISSUE TITLE
Fails to get last tag

### ISSUE THREAD

**Issue by jeremenichelli** [semantic-release/git#81]
For some reason semantic release is getting the last release tag incorrectly.

In my case it gets `v27.5.0` when the last version is `v27.5.1`, which is correctly pushed in GitHub repository. Later the release fails because the packages tries to push `v27.5.1` but it already exists.

We had to move to manual releases just because of this, and there's apparently no way to break this missed release cycle. I'm pretty sure this is a bug on this utility but couldn't figure out which one, and sadly I can't provide much more details since the repo and packages are private.

**Comment by pvdlg** [comment]
semantic-release will look only at tags in the history of the release branch.
What do you get from `git merge-base --is-ancestor v27.5.1 master`?

It's possible that you rebased or squashed the commit associated with the tag `v27.5.1`, so the tag object still exists in your repository but there the commit associated with it is not in `master`'s history.

If you actually made a release `v27.5.1` before, make sure the `v27.5.1` tag is associated with the last commit on `master` at the time of the release.

**Comment by jeremenichelli** [comment]
Good call, will check the tags and come back here.

Thanks for your support and for your work on this amazing tool :)

**Comment by jeremenichelli** [comment]
@pvdlg I ran that command and saw nothing on the terminal, though I ran it using a tag that didn't have this release issue on master and got the same. Am I suppose to see something special? How do I make sure my last release tag is associated with `master` branch?

**Comment by pvdlg** [comment]
The output might depends in the version of git you are using.
To be sure check the exit code of that command.
```bash
git merge-base --is-ancestor v27.5.1 master
echo $?
// => Return 0 if in history, something else otherwise
```

**Comment by jeremenichelli** [comment]
Cool, yeah I just re-pushed the tag and the return value is `0`, hope this fixes our next release. I'll come here later to confirm if this solved the solution, also it would be good if you had a troubleshooting document for this type of cases so we don't bother you that much. I would love to contribute but I don't have enough knowledge to do it.

Thanks again for your help @pvdlg.
